services:
  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379" 
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data 

volumes:
  redis_data:
