// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package portfolio

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Portfolio struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Name          string             `json:"name"`
	InvestedValue pgtype.Text        `json:"invested_value"`
	CurrentValue  pgtype.Text        `json:"current_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Stock struct {
	ID            uuid.UUID          `json:"id"`
	PortfolioID   uuid.UUID          `json:"portfolio_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Symbol        string             `json:"symbol"`
	Name          string             `json:"name"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	PurchasePrice pgtype.Numeric     `json:"purchase_price"`
	PurchaseDate  time.Time          `json:"purchase_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
