// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package portfolio

import (
	"context"
)

type Querier interface {
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
}

var _ Querier = (*Queries)(nil)
