// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package stocks

import (
	"context"
)

type Querier interface {
	AddStock(ctx context.Context, arg AddStockParams) (Stock, error)
	DeleteStock(ctx context.Context, arg DeleteStockParams) error
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
}

var _ Querier = (*Queries)(nil)
