server:
  host: "0.0.0.0"
  port: 8080
  read_timeout_seconds: 15
  write_timeout_seconds: 15

database:
  host: "localhost"
  port: 5432
  user: "portfolio_user"
  password: "secure_password_here"
  dbname: "portfolio_db"
  sslmode: "disable"   

auth:
  jwt_secret: "your_jwt_secret_key"
  token_expiry_minutes: 60

external_apis:
  stock_data:
    base_url: "https://api.stockprovider.com/v1"
    api_key: "your_stock_api_key"

logging:
  level: "info"  
cache:
  redis:
    enabled: true
    host: "localhost"
    port: 6379
    password: ""
    db: 0
