// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: portfolio.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolio (
user_id,name,invested_value,current_value
) VALUES ($1,$2,$3,$4) RETURNING id,user_id,name,invested_value,current_value,created_at,updated_at
`

type CreatePortfolioParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Name          string      `json:"name"`
	InvestedValue pgtype.Text `json:"invested_value"`
	CurrentValue  pgtype.Text `json:"current_value"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, createPortfolio,
		arg.UserID,
		arg.Name,
		arg.InvestedValue,
		arg.CurrentValue,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.InvestedValue,
		&i.CurrentValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
